smoker/config/routes.rb
Rails.application.routes.draw do
  root to: 'smoking_areas#index'

  get "service/about"
  get "service/contact"
  resources :smoking_areas do
    collection do
      get :list
      get :locale
    end
  end
end

smoker/app/models/smoking_area.rb
class SmokingArea < ActiveRecord::Base
  validates :name, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
end

smoker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

smoker/app/controllers/service_controller.rb
class ServiceController < ApplicationController
end

smoker/app/controllers/smoking_area_controller.rb
class SmokingAreaController < ApplicationController
  def index
    @smoking_areas = SmokingArea.all

    @hash = Gmaps4rails.build_markers(@smoking_areas) do |smoking_area, marker|
      marker.lat smoking_area.latitude
      marker.lng smoking_area.longitude
      marker.infowindow smoking_area.name
      marker.json({title: smoking_area.name})
    end
  end

  def new
    @smoking_area = SmokingArea.new
  end

  def create
    @smoking_area = SmokingArea.new(smoking_area_params)

    if @smoking_area.save
      redirect_to :action => 'index'
    else
      render 'new'
    end
  end

  private
  def smoking_area_params
    params.require(:smoking_area).permit(:name, :address, :latitude, :longitude)
  end
end

smoker/app/controllers/smoking_areas_controller.rb
class SmokingAreasController < ApplicationController
  def index
    @smoking_areas = SmokingArea.all

    @hash = Gmaps4rails.build_markers(@smoking_areas) do |smoking_area, marker|
      marker.lat smoking_area.latitude
      marker.lng smoking_area.longitude
      marker.infowindow smoking_area.name
      marker.json({title: smoking_area.name})
    end
  end

  def list
    @smoking_areas = SmokingArea.all
  end

  def show
    @smoking_area = SmokingArea.find(params[:id])
  end

  def new
    @smoking_area = SmokingArea.new
  end

  def create
    @smoking_area = SmokingArea.new(smoking_area_params)

    if @smoking_area.save
      redirect_to :action => 'index'
    else
      render 'new'
    end
  end

  def edit
    @smoking_area = SmokingArea.find(params[:id])
  end

  def update
    @smoking_area = SmokingArea.find(params[:id])
    if @smoking_area.update(smoking_area_params)
      redirect_to smoking_area_url(@smoking_area)
    else
      render 'edit'
    end
  end

  def destroy
    @smoking_area = SmokingArea.find(params[:id])
    @smoking_area.destroy
    redirect_to :smoking_areas
  end

  private
  def smoking_area_params
    params.require(:smoking_area).permit(:name, :address, :latitude, :longitude)
  end
end

smoker/app/helpers/application_helper.rb
module ApplicationHelper
end

smoker/app/helpers/service_helper.rb
module ServiceHelper
end

smoker/app/helpers/smoking_areas_helper.rb
module SmokingAreasHelper
end

smoker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "smoker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

    <%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" %>
    <%= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <%= javascript_include_tag "application" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </head>
  <body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Smoker", root_path, :class => "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to t("defaults.home"), root_path, :class => "glyphicon glyphicon-home" %></li>
            <li><%= link_to t("defaults.about"), service_about_path, :class => "glyphicon glyphicon-info-sign" %></li>
            <li><%= link_to t("defaults.contact"), service_contact_path, :class => "glyphicon glyphicon-envelope" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to t("defaults.create_smoking_area"), new_smoking_area_path, :class => "glyphicon glyphicon-saved" %></li>
                <li><%= link_to t("defaults.list_smoking_area"), list_smoking_areas_path, :class => "glyphicon glyphicon-th-list" %></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase">

      <br>
      <div class="page-header">
        <%= yield %>
      </div>

      <div class="page-footer">
        <p align="center">Copyright (C) 2015 ymatsumo All Rights Reserved.</p>
      </div>

    </div> <!-- /container -->
  </body>
</html>

smoker/app/views/service/about.html.erb
<h2><%= t ".title" %></h2>

<div class="well bs-component">
Smokerは喫煙者のためのサイトです。
</div>

smoker/app/views/service/contact.html.erb
<h2><%= t ".title" %></h2>

<div class="well bs-component">
</div>

smoker/app/views/smoking_areas/_form.html.erb
<% if @smoking_area.errors.any? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <ul>
      <% @smoking_area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well bs-component">
  <%= form_for @smoking_area, html: {class: "form-horizontal"} do |f| %>
    <fieldset>
      <div class="form-group">
        <%= f.label :name, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :name, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :address, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :address, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :latitude, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :latitude, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :longitude, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :longitude, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= link_to t(".get_locale"), {action: "locale"}, remote: true, :class => "btn btn-warning" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.button t(".reset"), :type => "reset", :class => "btn btn-default" %>
          <%= f.button :type => "submit", :class => "btn btn-primary" %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

smoker/app/views/smoking_areas/_googlemap.html.erb
<div class="map_container">
  <div id="map" class="map_canvas"></div>
</div>

<script type="text/javascript">
  var handler = Gmaps.build('Google');
  handler.buildMap( {provider: {}, internal: {id: 'map'}}, function(){
    if (navigator.geolocation)
      navigator.geolocation.getCurrentPosition(displayOnMap);
  });

  function displayOnMap(position) {
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    markers[markers.length] = handler.addMarker( {
      lat: position.coords.latitude,
      lng: position.coords.longitude,
      picture: {
        url: "<%= asset_path "now.png" %>",
        width:  24,
        height: 24
      }
    });
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  };
</script>

smoker/app/views/smoking_areas/edit.html.erb
<h2><%= t ".title" %></h2>

<%= render "form" %>

smoker/app/views/smoking_areas/index.html.erb
<%= render 'googlemap' %>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th><%= t "activerecord.attributes.smoking_area.name" %></th>
      <th><%= t "activerecord.attributes.smoking_area.address" %></th>
    </tr>
  </thead>

  <tbody>
    <% @smoking_areas.each do |smoking_area| %>
    <tr>
      <td><%= smoking_area.name %></td>
      <td><%= smoking_area.address%></td>
    </tr>
    <% end %>
  </tbody>
</table>

smoker/app/views/smoking_areas/list.html.erb
<h2><%= t ".title" %></h2>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th><%= t "activerecord.attributes.smoking_area.name" %></th>
      <th><%= t "activerecord.attributes.smoking_area.address" %></th>
      <th><%= t "activerecord.attributes.smoking_area.latitude" %></th>
      <th><%= t "activerecord.attributes.smoking_area.longitude" %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @smoking_areas.each do |smoking_area| %>
    <tr>
      <td><%= smoking_area.name %></td>
      <td><%= smoking_area.address%></td>
      <td><%= smoking_area.latitude %></td>
      <td><%= smoking_area.longitude %></td>
      <th><%= link_to t(".edit"), edit_smoking_area_path(smoking_area), :class => "btn btn-info" %></th>
      <th><%= link_to t(".destroy"), smoking_area_path(smoking_area), :method => :delete, :data => {confirm: t(".confirm")}, :class => "btn btn-danger" %></th>
    </tr>
    <% end %>
  </tbody>
</table>

smoker/app/views/smoking_areas/locale.js.erb
$(function(){
  navigator.geolocation.getCurrentPosition(
    function(position){
      var latitude = position.coords.latitude;
      var longitude = position.coords.longitude;
      latitude = Math.floor(latitude * 1000000) / 1000000;
      longitude = Math.floor(longitude * 1000000) / 1000000;
      $('#smoking_area_latitude').val(latitude);
      $('#smoking_area_longitude').val(longitude);
    }
  );
});

smoker/app/views/smoking_areas/new.html.erb
<h2><%= t ".title" %></h2>

<% if @smoking_area.errors.any? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <ul>
      <% @smoking_area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well bs-component">
  <%= form_for @smoking_area, :url => {action: "create"}, :html => {class: "form-horizontal"} do |f| %>
    <fieldset>
      <div class="form-group">
        <%= f.label :name, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :name, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :address, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :address, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :latitude, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :latitude, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :longitude, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :longitude, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= link_to t(".get_locale"), {action: "locale"}, remote: true, :class => "btn btn-warning" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.button t(".reset"), :type => "reset", :class => "btn btn-default" %>
          <%= f.button :type => "submit", :class => "btn btn-primary" %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

smoker/app/views/smoking_areas/show.html.erb
<h2><%= t ".title" %></h2>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th><%= t "activerecord.attributes.smoking_area.name" %></th>
      <th><%= t "activerecord.attributes.smoking_area.address" %></th>
      <th><%= t "activerecord.attributes.smoking_area.latitude" %></th>
      <th><%= t "activerecord.attributes.smoking_area.longitude" %></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @smoking_area.name %></td>
      <td><%= @smoking_area.address%></td>
      <td><%= @smoking_area.latitude %></td>
      <td><%= @smoking_area.longitude %></td>
    </tr>
  </tbody>
</table>